services:
  - type: web
    name: ruiru-prime-properties
    runtime: docker
    plan: free
    region: frankfurt
    envVars:
      - key: PORT
        value: "10000"
      - key: DB_DRIVER
        value: "sqlite"
